{
 "title": "Dashboard",
 "time": { "from": "1994-11-12T11:58:44.822Z", "to": "2002-10-16T18:36:05.590Z" },
 "panels": [
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(price) FROM dashboard_dolarprice LIMIT 50 "
    }
   ]
  },
  {
   "title": "Day 10/01 in each year",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT extract('YEAR' FROM date_registered) AS Ano, price\r\nFROM dashboard_dolarprice\r\nWHERE extract('MONTH' FROM date_registered) = 1\r\n  AND extract('DAY' FROM date_registered) = 10\r\n  AND extract('YEAR' FROM date_registered) BETWEEN 1995 AND 2023\r\nORDER BY Ano;"
    }
   ]
  },
  {
   "title": "Latest Prices",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT price, date_registered FROM dashboard_dolarprice ORDER BY date_registered DESC"
    }
   ]
  },
  {
   "title": "Average Dolar Price per Month",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(price), EXTRACT('MONTH' FROM date_registered) as month, extract('YEAR' FROM date_registered) as year \nFROM dashboard_dolarprice \nGROUP BY year, month \nORDER BY year DESC, month DESC\nLIMIT 50 "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(price) FROM dashboard_dolarprice"
    }
   ]
  },
  {
   "title": "Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(price) FROM dashboard_dolarprice"
    }
   ]
  },
  {
   "title": "Dolar Price Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT price, date_registered FROM dashboard_dolarprice "
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(price) FROM dashboard_dolarprice GROUP BY date_registered"
    }
   ]
  },
  {
   "title": "Variação do mínimo, média e máximo ao longo do tempo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    date_registered,\r\n    MIN(price) OVER (ORDER BY date_registered) AS min_price,\r\n    price AS current_price,\r\n    AVG(price) OVER (ORDER BY date_registered) AS avg_price,\r\n    MAX(price) OVER (ORDER BY date_registered) AS max_price\r\nFROM dashboard_dolarprice\r\nORDER BY date_registered;"
    }
   ]
  },
  {
   "title": "Média móvel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_registered,\r\n    price,\r\n    AVG(price) OVER (ORDER BY date_registered ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS diaria_avg,\r\n    AVG(price) OVER (ORDER BY date_registered ROWS BETWEEN 7 PRECEDING AND CURRENT ROW) AS semanal_avg,\r\n    AVG(price) OVER (ORDER BY date_registered ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS mensal_avg,\r\n    AVG(price) OVER (ORDER BY date_registered ROWS BETWEEN 180 PRECEDING AND CURRENT ROW) AS semestral_avg,\r\n    AVG(price) OVER (ORDER BY date_registered ROWS BETWEEN 365 PRECEDING AND CURRENT ROW) AS anual_avg   \r\nFROM\r\n    dashboard_dolarprice\r\nORDER BY\r\n    date_registered;\r\n"
    }
   ]
  }
 ]
}